config/routes.rb
Rails.application.routes.draw do
  # get 'students/new'
  # get 'students/index'
  # get 'students/show'
  # get 'students/:id/update'
  # get 'students/delete'
  # get 'students/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :students

  get 'teachers/new', to: 'teachers#new'
  get 'teachers', to: 'teachers#index'
  post 'teachers', to: 'teachers#create'
  get 'teachers/:id', to: 'teachers#show'
  put 'teachers/:id', to: 'teachers#update'
  get 'teachers/:id/edit', to: 'teachers#edit'
  delete 'teachers/:id', to: 'teachers#delete'

  # Defines the root path route ("/")
  root "students#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :address, presence: true
  validates :school, presence: true
  validates :phone, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :medium, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # add_flash_types :info, :error, :warning
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new

  end

  def index
    @students = Student.all
    # flash.now[:notice] = "User not found."
  end

  def show
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(students_param)
    if @student.update(students_param)
      flash[:success] = "Successfully Updated"
      redirect_to students_path
    else
      flash[:danger] = "Failed to Update user: #{error_messages(@user)}"
      redirect_to students_path
    end
    rescue StandardError => e
      flash[:danger] = "An error occurred: #{e.message.to_s}"
    redirect_to students_path
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    if @student.destroy
      flash[:success] = "Successfully Deleted"
      redirect_to students_path
    else
      flash[:danger] = "Failed to Delete user: #{error_messages(@user)}"
      redirect_to students_path
    end
  rescue StandardError => e
    flash[:danger] = "An error occurred: #{e.message.to_s}"
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(students_param)
    if @student.save
      flash[:success] = "Successfully Created"
      redirect_to students_path
    else

      # binding.pry

      flash[:danger] = "Failed to create user: #{@student.errors.messages }"
      # redirect_to new_student_path
      render :new, status: :unprocessable_entity
    end
    # rescue StandardError => e
    #   flash[:danger] = "An error occurred: #{e.message.to_s}"
    #   redirect_to students_path
  end

  private

  def students_param
    params.require(:student).permit(:name, :age, :address, :school, :std, :medium, :email, :phone)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def average_age
    students = Student.all
    total_age = students.pluck(:age).map(&:to_i).sum
    total_age / students.length.to_f
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

app/views/students/_form.html.erb
<div class="container justify-content-center">
    <div class="card p-4 col-6 mx-auto my-2">
        <%= form_with(model: student) do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: "form-label" %>
                <%= form.text_field :name, class: "form-control",required: true , placeholder: "Enter student name"%>
            </div>
            <div class="mb-3">
                <%= form.label :address, class: "form-label" %>
                <%= form.text_field :address, class: "form-control",required: true , placeholder: "Enter student address" %>
            </div>
            <div class="mb-3 d-flex">
                <div class="px-1">
                    <%= form.label :age, class: "form-label" %>
                    <%= form.number_field :age, class: "form-control",required: true , placeholder: "Enter student age" %>
                </div>
                <div class="px-1">
                    <%= form.label "class", class: "form-label" %>
                    <%= form.number_field :std, class: "form-control",required: true , placeholder: "Enter class" %>
                </div>
            </div>
            <div class="mb-3">
                <%= form.label :school, class: "form-label" %>
                <%= form.text_field :school, class: "form-control",required: true , placeholder: "Enter school" %>
            </div>
            <div class="mb-3">
                <%= form.label :medium, class: "form-label" %>
                <%= form.select :medium, [['Bengali', 'bengali'], ['English', 'english'], ['Hindi', 'hindi']], { include_blank: :medium }, class: 'form-select form-select-md', aria: { label: 'Small select example' } %>
            </div>
            <div class="mb-3">
                <%= form.label :email, class: "form-label" %>
                <%= form.email_field :email, class: "form-control",required: true , placeholder: "Enter email" %>
            </div>
            <div class="mb-3">
                <%= form.label :phone, class: "form-label" %>
                <%= form.number_field :phone, class: "form-control",required: true , placeholder: "Enter phone number" %>
            </div>
        <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
  

app/views/students/_navbar.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>CRUD</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=<%= students_path %>>Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href=<%= new_student_path %>>New Student</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>      

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

app/views/students/edit.html.erb
<%= render partial: 'navbar' %>
<h1 class="text-center my-2">Update <%= @student.name %></h1>
<%= render partial: 'form', locals: { student: @student } %>

app/views/students/index.html.erb
<%= render 'navbar' %>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
  <strong> <%= value %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<div class="container">
  <h1 class="text-center my-4">All Students</h1>
  <div class="container">
    <h4>Total No of Students :<strong> <%= @students.count %> </strong> </h4>
    <h4>Average age of Students :<strong> <%= average_age %> </strong> </h4>
    <!-- <%= link_to "New Student", new_student_path, class: "btn btn-success" %> -->
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Address</th>
          <th>Class</th>
          <th>School</th>
          <th>Medium</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.age %></td>
            <td><%= student.address %></td>
            <td><%= student.class %></td>
            <td><%= student.school %></td>
            <td><%= student.medium %></td>
            <td><%= student.email %></td>
            <td><%= student.phone %></td>
            <td class="d-flex">
              <%= link_to "Edit", edit_student_path(student), class: "btn btn-primary btn-sm mx-1" %>
              <%= button_to "Delete", student, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/students/new.html.erb
<%= render partial: 'navbar' %>
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
  <strong> <%= value %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<div class="container">
    <h1 class="text-center my-2">Create New Student</h1>
    <%= render partial: 'form', locals: { student: @student } %>
</div>

app/views/students/show.html.erb
<h1>Student Details : <%= @student.name %></h1>
<p>Age: <%= @student.age %></p>
<p>Address: <%= @student.address %></p>
<%= >